"""
PlatformIO pre-build script: reads .env (KEY=VALUE, one per line) and
generates src/secrets.h with the values as C string macros.

.env is the single source of truth and is gitignored. src/secrets.h is
generated on every build and is also gitignored -- never commit either file.
"""
import os

Import("env")  # noqa: F821  (provided by PlatformIO at script execution time)

PROJECT_DIR = env.get("PROJECT_DIR")  # noqa: F821
ENV_PATH = os.path.join(PROJECT_DIR, ".env")
OUT_PATH = os.path.join(PROJECT_DIR, "src", "secrets.h")

REQUIRED_KEYS = ("TBANK_TOKEN", "WIFI_SSID", "WIFI_PASSWORD")

# Optional: which chart style to render ("candles" or "line"). Defaults to
# "candles" when unset or set to something unrecognized.
CHART_TYPE_KEY = "CHART_TYPE"
CHART_TYPE_DEFAULT = "candles"
CHART_TYPE_VALUES = ("candles", "line")


def parse_env(path):
    values = {}
    if not os.path.isfile(path):
        return values
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, value = line.partition("=")
            key = key.strip()
            value = value.strip().strip('"').strip("'")
            values[key] = value
    return values


def c_string_literal(value):
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return '"' + escaped + '"'


def main():
    values = parse_env(ENV_PATH)
    missing = [k for k in REQUIRED_KEYS if not values.get(k)]
    if missing:
        raise SystemExit(
            "gen_secrets.py: missing required key(s) in .env: {}\n"
            "Create a .env file at the project root with:\n"
            "  TBANK_TOKEN=...\n"
            "  WIFI_SSID=...\n"
            "  WIFI_PASSWORD=...".format(", ".join(missing))
        )

    chart_type = values.get(CHART_TYPE_KEY, "").strip().lower()
    if chart_type not in CHART_TYPE_VALUES:
        chart_type = CHART_TYPE_DEFAULT

    lines = [
        "#pragma once",
        "// Auto-generated by tools/gen_secrets.py from .env -- do not edit, do not commit.",
        "",
    ]
    for key in REQUIRED_KEYS:
        lines.append("#define SECRET_{} {}".format(key, c_string_literal(values[key])))
    lines.append("#define SECRET_CHART_TYPE {}".format(c_string_literal(chart_type)))
    lines.append("")

    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print("gen_secrets.py: wrote {}".format(OUT_PATH))


main()
