"""
PlatformIO pre-build script: reads .env (KEY=VALUE, one per line) and
generates src/secrets.h with the values as C string macros.

.env is the single source of truth and is gitignored. src/secrets.h is
generated on every build and is also gitignored -- never commit either file.
"""
import os

Import("env")  # noqa: F821  (provided by PlatformIO at script execution time)

PROJECT_DIR = env.get("PROJECT_DIR")  # noqa: F821
ENV_PATH = os.path.join(PROJECT_DIR, ".env")
OUT_PATH = os.path.join(PROJECT_DIR, "src", "secrets.h")

REQUIRED_KEYS = ("TBANK_TOKEN", "WIFI_SSID", "WIFI_PASSWORD")

# Optional: which chart style to render ("candles" or "line"). Defaults to
# "candles" when unset or set to something unrecognized.
CHART_TYPE_KEY = "CHART_TYPE"
CHART_TYPE_DEFAULT = "candles"
CHART_TYPE_VALUES = ("candles", "line")

# Optional: which MOEX instrument to track. Ticker is resolved to a figi at
# startup via InstrumentsService/FindInstrument (first API-tradable match
# wins) and is also used as the on-screen title.
INSTRUMENT_TICKER_KEY = "INSTRUMENT_TICKER"
INSTRUMENT_TICKER_DEFAULT = "SiU6"

# Optional: candle bucket size for the chart. Maps to the T-Bank REST
# CandleInterval enum, the duration of one candle in seconds (used to size
# the lookback window: APP_CANDLES_MAX_POINTS * seconds), and a short label
# for the on-screen chart title (e.g. "last 24h").
CANDLE_INTERVAL_KEY = "CANDLE_INTERVAL"
CANDLE_INTERVAL_DEFAULT = "minute"
CANDLE_INTERVAL_MAP = {
    "minute": ("CANDLE_INTERVAL_1_MIN", 60, "m"),
    "hour": ("CANDLE_INTERVAL_HOUR", 3600, "h"),
    "day": ("CANDLE_INTERVAL_DAY", 86400, "d"),
    "week": ("CANDLE_INTERVAL_WEEK", 604800, "w"),
}


def parse_env(path):
    values = {}
    if not os.path.isfile(path):
        return values
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, value = line.partition("=")
            key = key.strip()
            value = value.strip().strip('"').strip("'")
            values[key] = value
    return values


def c_string_literal(value):
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return '"' + escaped + '"'


def main():
    values = parse_env(ENV_PATH)
    missing = [k for k in REQUIRED_KEYS if not values.get(k)]
    if missing:
        raise SystemExit(
            "gen_secrets.py: missing required key(s) in .env: {}\n"
            "Create a .env file at the project root with:\n"
            "  TBANK_TOKEN=...\n"
            "  WIFI_SSID=...\n"
            "  WIFI_PASSWORD=...".format(", ".join(missing))
        )

    chart_type = values.get(CHART_TYPE_KEY, "").strip().lower()
    if chart_type not in CHART_TYPE_VALUES:
        chart_type = CHART_TYPE_DEFAULT

    ticker = values.get(INSTRUMENT_TICKER_KEY, "").strip() or INSTRUMENT_TICKER_DEFAULT

    candle_interval = values.get(CANDLE_INTERVAL_KEY, "").strip().lower()
    if candle_interval not in CANDLE_INTERVAL_MAP:
        candle_interval = CANDLE_INTERVAL_DEFAULT
    candle_interval_enum, candle_interval_seconds, candle_interval_label = (
        CANDLE_INTERVAL_MAP[candle_interval]
    )

    lines = [
        "#pragma once",
        "// Auto-generated by tools/gen_secrets.py from .env -- do not edit, do not commit.",
        "",
    ]
    for key in REQUIRED_KEYS:
        lines.append("#define SECRET_{} {}".format(key, c_string_literal(values[key])))
    lines.append("#define SECRET_CHART_TYPE {}".format(c_string_literal(chart_type)))
    lines.append("#define SECRET_INSTRUMENT_TICKER {}".format(c_string_literal(ticker)))
    lines.append("#define SECRET_CANDLE_INTERVAL {}".format(c_string_literal(candle_interval_enum)))
    lines.append("#define SECRET_CANDLE_INTERVAL_SECONDS {}".format(candle_interval_seconds))
    lines.append("#define SECRET_CANDLE_INTERVAL_LABEL {}".format(c_string_literal(candle_interval_label)))
    lines.append("")

    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print("gen_secrets.py: wrote {}".format(OUT_PATH))


main()
